version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
      - .env.development
    environment:
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    env_file:
      - .env.development
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${LOCAL_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${LOCAL_MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data:
